# nixpacks.toml

[phases.setup]
# Install tesseract (and any other system packages you need)
packages = ["tesseract"]

[phases.build]
# Install your Python dependencies
commands = ["pip install -r requirements.txt"]

[phases.start]
# Depending on your setup:
# - If you use separate services/procfile, omit these.
# - If you run both in one container:
commands = ["python bot.py", "python worker.py"]
