# nixpacks.toml

[phases.setup]
# Install tesseract (and any other system packages you need)
packages = ["tesseract", "ffmpeg"]

[phases.build]
# Install your Python dependencies
commands = ["pip install -r requirements.txt"]


