# nixpacks.toml
[phases.setup]
# This tells Nixpacks to install the tesseract binary
packages = ["tesseract"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["python bot.py", "python worker.py"]
